### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by adam-palazzo** [orbitdb/orbit-bot#4]
I know this is a WIP, but having it on NPM eventually would be nice :smile:

**Comment by RichardLitt** [comment]
I don't see any reason _not_ to do this. @haadcode?

**Comment by haadcode** [comment]
This repo a) was never used and b) haven't been touched in ages. Unless we plan to make this a thing and support it, I wouldn't publish it.

**Comment by RichardLitt** [comment]
Aight! I'll add a disclaimer.
